"""
tests/test_walkin.py — Walk-in approval flow tests

Covers:
  - guard creates a walk-in request
  - organizer approves → invite auto-created
  - guard can then use the QR to scan entry
  - organizer rejects a walk-in
  - non-owner organizer cannot approve
"""
import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession
from tests.helpers import auth_headers, create_space, link_guard_to_space

pytestmark = pytest.mark.asyncio


async def test_create_walkin_request(client: AsyncClient, db: AsyncSession):
    guard_headers = await auth_headers(client, db, "GUARD")
    org_headers   = await auth_headers(client, db, "ORGANIZER")
    space = await create_space(client, org_headers)
    await link_guard_to_space(client, db, guard_headers, space)

    resp = await client.post("/walkins/request", data={
        "space_id":     space["id"],
        "visitor_name": "Walk-In Visitor",
        "reason":       "Attending the event",
    }, headers=guard_headers)
    assert resp.status_code == 201
    data = resp.json()
    assert data["status"] == "PENDING"
    assert data["visitor_name"] == "Walk-In Visitor"


async def test_approve_walkin_creates_invite(client: AsyncClient, db: AsyncSession):
    """Approving a walk-in must create a real Invite with a QR token."""
    guard_headers = await auth_headers(client, db, "GUARD")
    org_headers   = await auth_headers(client, db, "ORGANIZER")
    space = await create_space(client, org_headers)
    await link_guard_to_space(client, db, guard_headers, space)

    walkin_resp = await client.post("/walkins/request", data={
        "space_id":     space["id"],
        "visitor_name": "Approved Visitor",
    }, headers=guard_headers)
    walkin_id = walkin_resp.json()["id"]

    approve_resp = await client.post(f"/walkins/approve/{walkin_id}", headers=org_headers)
    assert approve_resp.status_code == 200
    data = approve_resp.json()
    assert data["status"] == "APPROVED"
    assert "qr_token" in data
    assert "invite_id" in data


async def test_approved_walkin_qr_can_be_scanned(client: AsyncClient, db: AsyncSession):
    """The QR generated by an approved walk-in must work with the normal entry scan."""
    guard_headers = await auth_headers(client, db, "GUARD")
    org_headers   = await auth_headers(client, db, "ORGANIZER")
    space = await create_space(client, org_headers)
    await link_guard_to_space(client, db, guard_headers, space)

    walkin = await client.post("/walkins/request", data={
        "space_id":     space["id"],
        "visitor_name": "Scannable Visitor",
    }, headers=guard_headers)
    walkin_id = walkin.json()["id"]

    approval = await client.post(f"/walkins/approve/{walkin_id}", headers=org_headers)
    qr_token  = approval.json()["qr_token"]

    scan_resp = await client.post("/entry/scan", json={
        "qr_token": qr_token,
        "gate_id":  "GATE-WALKIN",
    }, headers=guard_headers)
    assert scan_resp.status_code == 200
    assert scan_resp.json()["status"] == "ALLOWED"


async def test_reject_walkin(client: AsyncClient, db: AsyncSession):
    guard_headers = await auth_headers(client, db, "GUARD")
    org_headers   = await auth_headers(client, db, "ORGANIZER")
    space = await create_space(client, org_headers)
    await link_guard_to_space(client, db, guard_headers, space)

    walkin = await client.post("/walkins/request", data={
        "space_id":     space["id"],
        "visitor_name": "Rejected Visitor",
    }, headers=guard_headers)
    walkin_id = walkin.json()["id"]

    resp = await client.post(f"/walkins/reject/{walkin_id}",
                             json={"note": "No capacity"}, headers=org_headers)
    assert resp.status_code == 200
    assert resp.json()["status"] == "REJECTED"


async def test_cannot_approve_already_approved(client: AsyncClient, db: AsyncSession):
    """Approving an already-approved request must return 400."""
    guard_headers = await auth_headers(client, db, "GUARD")
    org_headers   = await auth_headers(client, db, "ORGANIZER")
    space = await create_space(client, org_headers)
    await link_guard_to_space(client, db, guard_headers, space)

    walkin = await client.post("/walkins/request", data={
        "space_id":     space["id"],
        "visitor_name": "Double Approve",
    }, headers=guard_headers)
    walkin_id = walkin.json()["id"]

    await client.post(f"/walkins/approve/{walkin_id}", headers=org_headers)
    resp = await client.post(f"/walkins/approve/{walkin_id}", headers=org_headers)
    assert resp.status_code == 400
